config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :cashiers
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :products
  has_many :cashiers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
    belongs_to :admin
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
     before_action :authenticate_admin!
    
    def new
        @cashier = Cashier.new
    end
    
    def index
        @cashiers = Cashier.all
    end
    
    def edit
        @cashier = Cashier.find(params[:id])
        if @cashier.admin != current_admin
            redirect_to cashiers_path
        end
        
    end
    
    def create
        @cashier = Cashier.new(cashier_params)
        @cashier.admin = current_admin
        @cashier.save
       
       redirect_to @cashier
    end
    
    def view
        id = params[:id]
        @cashier = Cashier.find(id)
    end
    
    def show
        id = params[:id]
        @cashier = Cashier.find(id)
    end
    
    def update
        @cashier = Cashier.find(params[:id])
        @cashier.update(cashier_params)
        @cashier.save
        redirect_to @cashier
    end
    
    def destroy
        @cashier = Cashier.find(params[:id])
        @cashier.destroy
        
        redirect_to cashiers_path
    end
    
    private
        def cashier_params
            params.require(:cashier).permit(:name, :status)
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_admin!
    
    def new
        @product = Product.new
    end
    
    def index
        @products = Product.all
    end
    
    def edit
        @product = Product.find(params[:id])
        if @product.admin != current_admin
            redirect_to products_path
        end
        
    end
    
    def create
        @product = Product.new(product_params)
        @product.admin = current_admin
        @product.save
       
       redirect_to @product
    end
    
    def view
        id = params[:id]
        @product = Product.find(id)
    end
    
    def show
        id = params[:id]
        @product = Product.find(id)
    end
    
    def update
        @product = Product.find(params[:id])
        @product.update(product_params)
        @product.save
        redirect_to @product
    end
    
    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        
        redirect_to prodcts_path
    end
    
    private
        def product_params
            params.require(:product).permit(:name, :price, :status)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cashiers/_form.html.erb
<div class="col-md-4 col-md-offset-4">
    <%= simple_form_for @cashier do |f| %>
        <p>
            <%= f.input :name %>
        </p>
        <p>
            <%= f.input :status %>
        </p>
        <%= f.button :submit %>
        
    <% end %>

</div>

app/views/cashiers/edit.html.erb
<h1>Edit Cashier</h1>
<%= render 'form' %> 

app/views/cashiers/index.html.erb
<h1>Cashier Index</h1>
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Status</th>
        <th>Admin</th>
        <th>Action</th>
    </tr>
    <% @cashiers.each do |p| %>
        <tr>
            <td><%= p.id %></td>
            <td><%= p.name %></td>
            <td><%= p.status %></td>
            <td><%= if p.admin then p.admin.email else "NA" end %></td>
            <td><%= link_to "Show", cashier_path(p) %></td>

        </tr>
    <% end %>
</table> 

app/views/cashiers/new.html.erb
<h1>New Cashier</h1>
<%= render 'form' %> 

app/views/cashiers/show.html.erb
<h2>Show Cashier</h2>
<h3> Cashier #<%= @cashier.id %></h3>

<h4>Cashier name: <%= @cashier.name %></h4>


<p>
    Status: <%= if @cashier.status then "Active" else "Inactive" end %>
</p>

<%= link_to "Back to Index", cashiers_path %><br>
<%= link_to "Edit", edit_cashier_path(@cashier) %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid navbar-fnt">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ZSCH Bakery</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="https://lab3-shanelseedee.c9users.io/products/">Products List</a></li>
        <li><a href="https://lab3-shanelseedee.c9users.io/cashiers#">Cashiers List</a></li>
      </ul>
      
    <p class="navbar-text pull-right">
        <% if admin_signed_in? %>
          Logged in as <strong><%= current_admin.email %></strong>
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "navbar-link"%>
        <% else %>
          <%= link_to "Sign up", new_admin_registration_path, class: "navbar-link" %> |
          <%= link_to "Sign in", new_admin_session_path, class: "navbar-link" %>
        <% end %>
      </p> 

      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="col-md-4 col-md-offset-4">
    <%= simple_form_for @product do |f| %>
        <p>
            <%= f.input :name %>
        </p>
        <p>
            <%= f.input :price %>
        </p>
        <p>
            <%= f.input :status %>
        </p>
        <%= f.button :submit %>
        
    <% end %>

</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %> 

app/views/products/index.html.erb
<h1>Product Index</h1>
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    <% @products.each do |p| %>
        <tr>
            <td><%= p.id %></td>
            <td><%= p.name %></td>
            <td><%= p.price %></td>
            <td><%= p.status %></td>
            <td><%= link_to "Show", product_path(p) %></td>
        </tr>
    <% end %>
</table> 

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %> 

app/views/products/show.html.erb
<h2>Show Product</h2>
<h3> Product #<%= @product.id %></h3><br>

<h4><%= @product.name %></h4>

<p>
    Price: 
    <%= @product.price %>
</p>

<p>
    <%= if @product.status then "Active" else "Inactive" end %>
</p>
<%= link_to "Back to Index", products_path %><br>
<%= link_to "Edit", edit_product_path(@product) %>